# Generated by Django 5.1.1 on 2024-10-08 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vinos', '0003_alter_vino_intensidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ('nombre',), 'verbose_name': 'Usuarios', 'verbose_name_plural': 'Mis usuarios'},
        ),
        migrations.AlterModelOptions(
            name='vino',
            options={'ordering': ('nombre',), 'verbose_name': 'Vinos', 'verbose_name_plural': 'Mis vinos'},
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
