# Generated by Django 5.1.1 on 2024-10-11 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vinos', '0004_alter_usuario_options_alter_vino_options_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comentarios', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_vinos.usuario')),
                ('vinos', models.ManyToManyField(to='app_vinos.vino')),
            ],
        ),
    ]
