# Generated by Django 5.1.1 on 2024-10-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vinos', '0006_usuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cata',
            name='tipo_de_cata',
            field=models.CharField(choices=[('Blanco', 'Cata de Vinos Blancos'), ('Tinto', 'Cata de Vinos Tintos'), ('Online', 'Cata Online'), ('Empresa', 'Cata para empresas')], default='Blanco', max_length=20),
        ),
    ]
